# Generated by Django 5.2 on 2025-06-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, default='2a4ed2e9', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_id',
            field=models.CharField(blank=True, default='81aab81f', max_length=8, unique=True),
        ),
    ]
