# Generated by Django 5.2 on 2025-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, default='6558839a', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_id',
            field=models.CharField(blank=True, default='197ce425', max_length=8, unique=True),
        ),
    ]
