# Generated by Django 5.2 on 2025-06-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, default='aa1e91f9', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_id',
            field=models.CharField(blank=True, default='695350e3', max_length=8, unique=True),
        ),
    ]
