# Generated by Django 5.2 on 2025-06-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, default='3184e7f0', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_id',
            field=models.CharField(blank=True, default='2dfd5a87', max_length=8, unique=True),
        ),
    ]
