# Generated by Django 5.2 on 2025-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, default='8636a359', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_id',
            field=models.CharField(blank=True, default='e5429962', max_length=8, unique=True),
        ),
    ]
