# Generated by Django 5.2 on 2025-06-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_product_need_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedt',
            name='employee_code',
            field=models.CharField(blank=True, default='c167ac03', max_length=8, unique=True),
        ),
    ]
