# Generated by Django 5.2 on 2025-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeedt_employee_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productneedmain',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeedt',
            name='employee_code',
            field=models.CharField(blank=True, default='e6482a3d', max_length=8, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductNeedItem',
        ),
        migrations.DeleteModel(
            name='ProductNeedMain',
        ),
    ]
