# Generated by Django 5.2 on 2025-06-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_productneedmain_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedt',
            name='employee_code',
            field=models.CharField(blank=True, default='da021c6b', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product_need',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product_need',
            name='msg_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product_need',
            name='qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
