# Generated by Django 5.2 on 2025-06-06 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_client_client_id_and_more'),
        ('employee', '0005_alter_employeedt_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_need',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.site'),
        ),
        migrations.AlterField(
            model_name='employeedt',
            name='employee_code',
            field=models.CharField(blank=True, default='9449b399', max_length=8, unique=True),
        ),
    ]
