# Generated by Django 5.2 on 2025-06-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_product_need_site_alter_employeedt_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedt',
            name='employee_code',
            field=models.CharField(blank=True, default='2ba4c2c1', max_length=8, unique=True),
        ),
    ]
